fail_on_violations: true
javascript:
  enabled: true
  ignore_file: .hound/ignoredfiles
eslint:
  enabled: true
  config_file: .hound/eslintrc.json
  ignore_file: .hound/ignoredfiles
tslint:
  enabled: true
  config_file: .hound/tslint.json
  ignore_file: .hound/ignoredfiles
ruby:
  enabled: true
  config_file: .hound/rubocop.yml
  ignore_file: .hound/ignoredfiles
scss:
  enabled: true
  config_file: .hound/scss-lint.yml
  ignore_file: .hound/ignoredfiles
